from about import about
from auth import auth
from auth_redirect import auth_redirect
from bookmarklet import bookmarklet
from index import index
from login import login
from logout import logout
from new import new
from people import people
from piece import piece
from tools import tools
from app import app